# Generated by Django 5.2.7 on 2025-10-31 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id_playlist', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('plano', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('duracao', models.IntegerField(help_text='Duração em segundos')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.artista')),
            ],
        ),
        migrations.CreateModel(
            name='MusicaPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.musica')),
                ('id_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.playlist')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.usuario'),
        ),
        migrations.AddConstraint(
            model_name='musica',
            constraint=models.CheckConstraint(condition=models.Q(('duracao__gt', 0)), name='duracao_positiva'),
        ),
        migrations.AddConstraint(
            model_name='musicaplaylist',
            constraint=models.UniqueConstraint(fields=('id_musica', 'id_playlist'), name='pk_musica_playlist'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('id_usuario', 'id_playlist'), name='pk_playlist'),
        ),
    ]
