# Generated by Django 5.2.7 on 2025-11-06 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('nacionalidade', models.CharField(default='Desconhecida', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('duracao_segundos', models.IntegerField(help_text='Duração em segundos')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='musica.artista')),
            ],
        ),
        migrations.CreateModel(
            name='MusicaPlaylist',
            fields=[
                ('pk', models.CompositePrimaryKey('musica_id', 'playlist_id', 'usuario_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('playlist_id', models.IntegerField(unique=True)),
                ('usuario_id', models.IntegerField(unique=True)),
                ('ordem_na_playlist', models.IntegerField(unique=True)),
                ('musica_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.musica')),
                ('playlist', models.ForeignObject(from_fields=['playlist_id', 'usuario_id'], on_delete=django.db.models.deletion.CASCADE, to='musica.playlist', to_fields=['playlist_id', 'usuario_id'])),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='usuario_id',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='musica.usuario'),
        ),
        migrations.AddConstraint(
            model_name='musica',
            constraint=models.CheckConstraint(condition=models.Q(('duracao_segundos__gt', 0)), name='duracao_positiva'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('playlist_id', 'usuario_id'), name='pk_playlist_usuario'),
        ),
    ]
