# Generated by Django 5.2.7 on 2025-11-02 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('nacionalidade', models.CharField(default='Desconhecida', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('duracao_segundos', models.IntegerField(help_text='Duração em segundos')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='musica.artista')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='MusicaPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_na_playlist', models.IntegerField()),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.musica')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.playlist')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.usuario')),
            ],
        ),
        migrations.AddConstraint(
            model_name='musica',
            constraint=models.CheckConstraint(condition=models.Q(('duracao_segundos__gt', 0)), name='duracao_positiva'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('playlist_id', 'usuario'), name='pk_playlist'),
        ),
        migrations.AddConstraint(
            model_name='musicaplaylist',
            constraint=models.UniqueConstraint(fields=('musica', 'playlist', 'usuario'), name='pk_musica_playlist'),
        ),
        migrations.AddConstraint(
            model_name='musicaplaylist',
            constraint=models.UniqueConstraint(fields=('playlist', 'usuario', 'ordem_na_playlist'), name='unique_ordem_playlist'),
        ),
    ]
