# Generated by Django 5.2.7 on 2025-11-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicaplaylist',
            name='ordem_na_playlist',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='musicaplaylist',
            name='playlist_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='musicaplaylist',
            name='usuario_id',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='musicaplaylist',
            constraint=models.UniqueConstraint(fields=('ordem_na_playlist', 'playlist_id', 'usuario_id'), name='pk_musica_playlist_usuario'),
        ),
    ]
